#!/bin/sh
eval "$(ssh-agent -s)"
xautolock -time 15 -locker slock -detectsleep &
nitrogen --restore &
flameshot &
synology-drive &
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
exec bspwm
