#! /bin/sh

#bspc monitor HDMI-0 -s DP-0
#bspc wm -O DP-0 HDMI-0
bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor DP-0 -d I II III IV V VI VII VIII 
#bspc monitor HDMI-0 -d IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window rules
bspc rule -a Alacritty -o desktop='^1' 
bspc rule -a firefox -o desktop='^2' follow=on
bspc rule -a discord desktop='^9'
bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a Origin desktop='^7' floating=on
#bspc rule -a Discord desktop='^9'
bspc rule -a vlc desktop='^4' follow=on
bspc rule -a Xournalpp desktop='^3' follow=on
bspc rule -a Spotify desktop='^4' follow=on
bspc rule -a VSCodium desktop='^3' follow=on
bspc rule -a 'Microsoft Teams - Preview' desktop='^10' 
bspc rule -a Virt-manager desktop='^5' follow=on
bspc rule -a Steam desktop='^6' follow=on
bspc rule -a Thunderbird desktop='^8' 
bspc rule -a explorer.exe desktop='^7'
bspc rule -a Lutris desktop='^6' follow=on


# Autostart

#gsettings set org.cinnamon.desktop.default-applications.terminal exec alacritty
pgrep -x ssh-agent > /dev/null || ssh-agent -s
setxkbmap pl &
picom &
nitrogen --restore & 
pgrep -x parcellite > /dev/null || parcellite &
pgrep -x cloud-drive-ui > /dev/null || synology-drive  &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x Discord > /dev/null || discord &
# pgrep -x teams || flatpak run com.microsoft.Teams &
pgrep -x lxsession > /dev/null || lxsession &
pgrep -f firefox > /dev/null || firefox &
pgrep -x alacritty > /dev/null || alacritty &
pgrep -x thunderbird > /dev/null || thunderbird &
# pgrep -x firewall-applet > /dev/null || firewall-applet &
pgrep -x nm-applet > /dev/null || nm-applet &
$HOME/.config/polybar/launch.sh
