#! /bin/sh

xrandr --output DisplayPort-0 --primary --mode 1920x1080 --pos 1920x0 --rate 165 --rotate normal  --output DisplayPort-1 --mode 1920x1080 --pos 0x0 --rate 165 --rotate normal --output HDMI-A-0 --off --output HDMI-A-1 --off
bspc monitor DisplayPort-1 -s DisplayPort-0
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DisplayPort-0 -d I II III IV V VI VII 
bspc monitor DisplayPort-1 -d VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Window rules
bspc rule -a Alacritty -o desktop='^1' 
bspc rule -a firefox -o desktop='^2' follow=on
bspc rule -a discord desktop='^8'
bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a origin.exe floating=on
bspc rule -a origin floating=on
bspc rule 'Neko Saper' floating=on
#bspc rule -a Discord desktop='^9'
bspc rule -a vlc desktop='^4' follow=on
bspc rule -a Audacious desktop='^4' follow=on
bspc rule -a strawberry desktop='^4' follow=on
bspc rule -a Xournalpp desktop='^3' follow=on
bspc rule -a spotify desktop='^4' follow=on
bspc rule -a VSCodium desktop='^3' follow=on
bspc rule -a 'Microsoft Teams - Preview' desktop='^9' 
bspc rule -a Virt-manager desktop='^5' follow=on
bspc rule -a Steam desktop='^6' follow=on
bspc rule -a Thunderbird desktop='^10' 
bspc rule -a explorer.exe desktop='^7'
bspc rule -a Lutris desktop='^6' follow=on
bspc rule -a Zathura state=tiled


# Autostart

pgrep -x ssh-agent > /dev/null || ssh-agent -s
pgrep -x gpg-agent > /dev/null || gpg-agent
setxkbmap pl &
$HOME/.config/polybar/launch.sh
picom &
nitrogen --restore & 
pgrep -x parcellite > /dev/null || parcellite &
#pgrep -x cloud-drive-ui > /dev/null || synology-drive  &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x Discord > /dev/null || discord &
pgrep -x lxsession > /dev/null || lxsession &
pgrep -f firefox > /dev/null || firefox &
pgrep -f dunst > /dev/null || dunst &
#pgrep -f deluge-gtk > /dev/null || deluge &
#pgrep -f qbittorrent > /dev/null || qbittorrent &
pgrep -x alacritty > /dev/null || alacritty &
#pgrep protonmail > /dev/null || podman start protonmail-bridge &
# pgrep -x firewall-applet > /dev/null || firewall-applet &
pgrep -x thunderbird > /dev/null || thunderbird &
pgrep -x nm-applet > /dev/null || nm-applet 
