#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore 
bspc monitor DP-0 -d I II III IV V VI VII 
bspc monitor HDMI-0 -d VIII IX

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=0n
bspc rule -a discord desktop='^8'
bspc rule -a vlc desktop='^4' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Xournalpp desktop='^3' follow=on
bspc rule -a 'Microsoft Teams - Preview' desktop='^9' follow=on
bspc rule -a Virt-manager desktop='^5' follow=on
bspc rule -a Steam desktop='^6' follow=on
$HOME/.config/polybar/launch.sh
