#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore 
bspc monitor DP-0 -d  I II III IV V VI VII
bspc monitor HDMI-0 -d VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a firefox desktop='^2'
bspc rule -a Discord desktop='^8'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
