#!/bin/sh
#eval "$(ssh-agent -s)"
#xautolock -time 10 -locker slock &
setxkbmap pl &
picom &
xsetroot -cursor_name left_ptr
nitrogen --restore &
lxsession &
# flameshot &
# synology-drive &
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &
exec bspwm
