export PATH=$HOME/.scripts:$HOME/bin:/usr/local/bin:$PATH:$HOME/.local/bin
export BROWSER="firefox"
export ZSH="/home/szymon/.oh-my-zsh"
export EDITOR="vim"
export VISUAL="vim"
export VIDEO="mpv"
export IMAGE="eog"
export TERM=xterm-256color
export HISTORY_IGNORE="(ls|ll|la|l|cd|pwd|exit|cd ..|..|~|:q)"
export HISTSIZE=110000000
export SAVEHIST=100000000
