#!/usr/bin/zsh
if [ -f $1 ] ; then
  case $1 in
    *.tar.bz2)   tar -I pbzip2 -xvf $1   ;;
    *.tar.gz)    tar -I pigz -xvf $1   ;;
    *.bz2)       pbzip2 -d $1   ;;
    *.rar)       unrar x $1   ;;
    *.gz)        unpigz $1    ;;
    *.tar)       tar xf $1    ;;
    *.tbz2)      tar -I pbzip2 -xvf $1   ;;
    *.tgz)       tar -I pigz -xvf $1   ;;
    *.zip)       unzip $1     ;;
    *.Z)         uncompress $1;;
    *.7z)        7z x $1      ;;
    *.deb)       ar x $1      ;;
    *.tar.xz)    tar xf $1    ;;
    *.tar.zst)   tar xf $1    ;;
    *)           echo "'$1' cannot be extracted via ex()" ;;
  esac
else
  echo "'$1' is not a valid file"
fi

